### ISSUE TITLE
ctrl-k not yankable.

### ISSUE THREAD

**Issue by jots** [naturalethic/nemacs#1]
Is there a way to add items that are ctrl-k'd to the kill ring so that they can be yanked?
Common use case is for moving a line somewhere.

**Comment by naturalethic** [comment]
Looks like messing with the clipboard is going to be a bit hacky.  I'll see how well I can do this.  Thanks for the ticket!

**Comment by naturalethic** [comment]
I've added this and published, please update and give it a try.  However, I must mention that if you are not using a Mac it's still not going to work.  I don't have a windows or linux machine to test on.  Contributions are welcome from anyone who does.  I'm going to update the README to make that more clear.
