### ISSUE TITLE
save meta-d to clipboard

### ISSUE THREAD

**Issue by transtone** [naturalethic/nemacs#4]
how to save meta-d to clipboard like ctrl-y?

**Comment by naturalethic** [comment]
This is a mac-specific addon.  Are you on mac?

**Comment by transtone** [comment]
yes I'am on mac.

I'll get a try.

what's the addon's name? I can't find it.

**Comment by naturalethic** [comment]
https://marketplace.visualstudio.com/items?itemName=naturalethic.nemacs

**Comment by naturalethic** [comment]
These are the mappings for ctrl/meta(cmd)+d --- I'm not sure if its appropriate to put these in the clipboard.  What is normal emacs behaviour?

```
     {
        "key": "ctrl+d",
        "command": "deleteRight",
        "when": "editorTextFocus"
      },
      {
        "key": "cmd+d",
        "command": "deleteWordRight",
        "when": "editorTextFocus"
      },
```

**Comment by transtone** [comment]
In normal emacs, when I deleteWord with meta+d, it can be yank with ctrl-y.
